[[numix-icon-theme-git]]
url = "https://github.com/numixproject/numix-icon-theme.git"
commit = "a6e6bf9f1e4ee5bfd6dbd143fe33b650ea8e8e3a"

[[razercommander-git]]
url = "https://github.com/gabmus/razercommander"
commit = "04c7a6e72a7495a0006e85feb21ee2b14c067293"

[[zsh-theme-powerlevel10k-git]]
url = "https://github.com/romkatv/powerlevel10k.git"
commit = "36f3045d69d1ba402db09d09eb12b42eebe0fa3b"
